create many tables; connect to my postgres-docker; start writing psql…
M-Koscheev/urfu-project-smart-schedule-former pull request #1
Opened 2023-11-12 12:19 UTC by M-Koscheev

… functions

2023-11-12 12:43 UTC, unicoooorn reviewed
хорошо идешь, не останавливайся

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/connection.go
> +package database_func
назови пакет db

2023-11-12 12:43 UTC, unicoooorn commented on docker-compose.yml
> +  #     - POSTGRES_PASSWORD=postgres
нельзя коммитить в репу креды
репозиторий твой открытый и его видит кто угодно, то есть кто угодно может подключиться щас к твоей базе данных по твоим кредам
обычно их вытаскивают в переменные окружения (погугли)

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/connection.go
> +func CheckError(err error) {
бесполезная функция, лучше везде, где ее используешь, поставь проверку ошибки, так идиоматичнее)

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +	err = db.Ping()
смари как можно в го
```go
if err = db.Ping(); err != nil {
    slog.Error("test connection failed", slog.String("err", err.Error()))
}
```

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	err := row.Scan(&data)
тут тоже лучше сделать
```go
if err = db.Ping(); err != nil {
    slog.Error("test connection failed", slog.String("err", err.Error()))
}
```

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	req := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ANY(%s))", column, table, column, needed)
sql запросы помещаются в кавычки типа `, а не "
потому в кавычках у тебя символы типа % состоят из двух символов - \%

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +package database_func
у тебя слишком мелкое дробление на файлы, и все немного перемешано:
обычно создается пакет db или pool, в котором создается connection, а сами запросы ты делаешь уже из пакета, в котором выполняется логика программы

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	req := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ANY(%s))", column, table, column, needed)
и вообще не надо прятать голый sql запрос под метод, в го так не принято
в го если тебе нужно обратиться к базе, ты тут же в коде пишешь sql запрос и исполняешь его

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	req := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ANY(%s))", column, table, column, needed)
sql запрос называется на request, а query

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	req := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ANY(%s))", column, table, column, needed)
аргументы в запрос подставляются не так, а так
```go
query := `SELECT $1 FROM $2 WHERE $3 = ANY($4))`
row := db.QueryRow(req, column, table, column, needed)
```

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	row := db.QueryRow(req)
ты забыл сделать 
```go
defer row.Close()
```
утечка дескриптора!!!

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +		panic(err)
никаких чупапи муняня и паник, возвращаешь просто return false, err

2023-11-12 12:43 UTC, unicoooorn commented on migrations/competencies/tbl_competence.pgsql
>  ('Система контроля версий', 'Git, GitHub, GitLab, Bitbucket, Bazaar, CVS, Mercurial, Perforce, SourceForge, SVN'),
в миграциях БД не обогащается данными, в миграциях только создаются, редактируются и удаляются таблицы
для подобных штук надо делать отдельную папку sql и писать там sql-скрипты, а вот эти values вынести в yaml файл (успехов)

2023-11-12 12:43 UTC, unicoooorn commented on migrations/tbl_profession.psql
> +CREATE TABLE IF NOT EXISTS professions (
соедини всё в один файл миграции
миграции делятся не по табличкам, а по времени
у тебя со временнем может меняться схема, и тогда будут появляться новые миграции (например, migration_add_field_student_grade)

2023-11-12 12:43 UTC, unicoooorn commented on cmd/start.go
>  	"github.com/M-Koscheev/urfu-project-smart-schedule-former/internal/prof_func"
на будущее: если надо заимпортить пакет в снейккейсе, надо просто сделать алиас перед ним типа вот так
```go
prof "github.com/M-Koscheev/urfu-project-smart-schedule-former/internal/prof_func"
```
но лучше не делать пакеты с длинными называниями, в этом редко есть необходимость

2023-11-12 12:43 UTC, unicoooorn commented on docker-compose.debug.yml
> +      - 8080:8080
пашиму у тебя постгрес на 8080 порте... 5432 канонический и общепринятый порт для постгреса

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +	checkError(err)
опять же, вытащи из функции обработку ошибок и сделай явно

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +func GetKnowledgeList() string {
функции помимо string должна возвращать ошибку

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +		var t string
лучше покрасноречивее назвать перменные, я не понял, например, что они значат)))

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +	rows, err := db.Query("select * from competencies")
никогда не селекти *, в случае, если у тебя появятся новые аттрибуты, сканирование снизу может сломаться
если тебе нужен title и competency, то селекти title, competency

2023-11-12 12:43 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +			log.Fatal(err)
в go 1.21 теперь есть slog, и пользоваться надо им
если вкратце, то slog - это структурированный log, то есть у него есть уровень slog.Error, slog.Info, slog.Debug, slog.Warn, slog.Fatal
пример использования
```go
slog.Fatal("все накрылось нам пизда паникуем")
slog.Error("бля ошибка неприятно но программа работает дальше")
slog.Warn("слушай чет хуйня какая то предупреждаю это не норм но в целом похуй")
slog.Info("МЫ УСПЕШНО ПОДКЛЮЧИЛИСЬ В БАЗЕ ДАННЫХ")
slog.Debug("бесполезная информация для дебага")
```

2023-11-12 12:46 UTC, unicoooorn commented on internal/database_func/data_addition.go
> +		var t string
а еще можно пачкой их создавать 
```go
var t, k string
```

2023-11-12 12:47 UTC, M-Koscheev commented on internal/database_func/connection.go
> +package database_func
папку с пакетом тоже переименовать?

2023-11-12 12:49 UTC, M-Koscheev commented on docker-compose.yml
> +  #     - POSTGRES_PASSWORD=postgres
у меня в одном из файлов данные для подключения к БД. Что с ними делать, передавать в виде аргументов?

2023-11-12 12:56 UTC, M-Koscheev commented on internal/database_func/data_validation.go
> +	err := row.Scan(&data)
я, пожалуй, вынесу это в функцию создания подключения. Чтобы сразу удостовериться в подключении и не проверять его в дальнейшем

2023-11-12 13:06 UTC, M-Koscheev commented on internal/database_func/data_validation.go
> +	row := db.QueryRow(req)
это промежуточная функция)

2023-11-12 13:12 UTC, M-Koscheev commented on docker-compose.debug.yml
> +      - 8080:8080
Это порт локалхоста (проекта в целом)

2023-11-13 08:14 UTC, unicoooorn commented on cmd/start.go
>  func StartApp() {
лучше создать пакет app в internal, где ты создаешь с New свой апп, и с app.Start() его запускаешь
напомню: cmd - чисто панель управления, ты никакую логику там не пишешь, только создаешь компоненты и соединяешь их воедино

2023-11-13 08:14 UTC, unicoooorn commented on cmd/start.go
>  func StartApp() {
конструкторы в go пишутся так
```go
func New(db *db) *App {
    return &App{db: db}
```
где
```go
type App struct {
    db *db
}
```

2023-11-13 08:14 UTC, unicoooorn commented on cmd/start.go
>  func StartApp() {
и соответственно в cmd сделаешь
```go
pool := db.ConnectDB()
defer pool.Close()
service := app.New(pool)
if err := service.Start; err != nil {
    slog.Fatal("unable to start app", slog.String("err", err.Error())
}
```

2023-11-13 08:14 UTC, unicoooorn commented on internal/database_func/connection.go
> +package database_func
да, имя пакета = имя папки всегда

2023-11-13 08:14 UTC, unicoooorn commented on docker-compose.yml
> +  #     - POSTGRES_PASSWORD=postgres
данные для подключения к бд никогда нельзя хранить в коде, либо их передаешь через env переменные, либо как аргументы к твоей программе

2023-11-13 08:14 UTC, unicoooorn commented on docker-compose.debug.yml
> +      - 8080:8080
так у тебя это не будет работать
что такое "порт проекта"? тот, на которую фронт будет слать запросы? если да, то порт постгреса и должен оставаться 5432 - к нему обращаешься ты, а не фронтендерны
не говоря уже о том, что два разных процесса не могут слушать один и тот же порт, и у тебя это не зарабаотает

2023-11-13 08:14 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	err := row.Scan(&data)
можно в функцию подключения, но даже лучше поместить это в cmd после создания db

2023-11-13 08:14 UTC, unicoooorn commented on internal/database_func/data_validation.go
> +	err := row.Scan(&data)
как вариант, да

2023-11-14 12:12 UTC, M-Koscheev commented on internal/database_func/data_validation.go
> +	err := row.Scan(&data)
> можно в функцию подключения, но даже лучше поместить это в cmd после создания db

***поправка: в internal/app/start, т.к. в cmd не должно быть логики программы***
Означает ли это, что открывать базу данных (подключаться к ней) нужно в start.go, а далее оттуда уже передавать ее в функции? Сейчас я открываю базу данных для каждой функции по отдельности

2023-11-18 16:04 UTC, unicoooorn reviewed
в общем и целом сильно всё лучше стало, немного поправь, я прувну и вмерджим в мастер

2023-11-18 16:04 UTC, unicoooorn commented on migrations/db_creation.psql
> +-- following sql naming convention tables names should be
все комментарии из этого файла стоит удалить

2023-11-18 16:04 UTC, unicoooorn commented on internal/db/connection.go
> +	return db, err
```go
return sql.Open("postgres", psqlconn)
```

2023-11-18 16:04 UTC, unicoooorn commented on internal/db/connection.go
> +	// connection string
коментарии бесполезнейшие, удали

2023-11-18 16:04 UTC, unicoooorn commented on internal/db/connection.go
> +func ConnectToDatabase() (*sql.DB, error) {
Название CreateConnection сильно лучше звучит
Но если оставлять в текущем виде, то хотя бы ConnectToDB

2023-11-18 16:04 UTC, unicoooorn commented on internal/db/connection.go
> +	host     = "localhost"
это что блядь креды в файле с кодом?
так нельзя, ты должен создавать .env файлы локально и из них с помощью os.Getenv() брать креды

2023-11-18 16:04 UTC, unicoooorn commented on internal/db/connection.go
> +	host     = "localhost"
погугли вообще enviroment-переменные

2023-11-18 16:04 UTC, unicoooorn commented on internal/app/start.go
> +type App struct {
структуру и конструктор норм сделал, только структура обычно в самом начале файла, дальше конструктор, дальше остальыне методы

2023-11-18 16:04 UTC, unicoooorn commented on internal/app/start.go
> +func (app App) greet(w http.ResponseWriter, r *http.Request) {
у тебя ресивер (который app App) передается по копированию, то есть на каждый метод структура копируется
не думаю, что ты такого поведения ожидал - с таким подходом ты не сможешь обновлять поля структуры, например
замени на (app *App)

2023-11-18 16:04 UTC, unicoooorn commented on internal/app/split_knowledge.go
> +func (app App) AddKnowledge(input string) error {
верни методы app внутрь App, не надо на файлы их разносить

2023-11-18 16:04 UTC, unicoooorn commented on internal/app/data_validation.go
> +package app
аналогично, верни в файл App

2023-11-18 16:04 UTC, unicoooorn commented on docker-compose.yml
> -      - 5432:5432
правильно что дб вынес из докер-компоуза, я чет сам пропустил
обычно бдшки не поднимают вместе с программами, они крутятся вообще на других машинах

2023-11-18 16:04 UTC, unicoooorn commented on internal/app/data_addition.go
> +func (app App) AddData(table string, needed string, column string) (sql.Result, error) {
аналогично, верни в файл App
не бойся длинных файлов, делить на файлы надо исходя из логики, а не из стремления сократить число кода в файле)

2023-11-18 16:05 UTC, unicoooorn commented
ну и да, чувак, коммить почаще и более мелкие изменения
это хорошая привычка, она позволяет откатываться по версим локально и в удаленном репозитории (могу научить, если сам не нагуглишь)

2023-11-18 16:11 UTC, unicoooorn commented on internal/db/connection.go
> +func ConnectToDatabase() (*sql.DB, error) {
поясню: connectToDB звучит как функция, которая не должна ничего возвращат
а createConnection звучит так, как будто ты создаешь соединение, и тут же его получаешь так и происходит)

2023-11-18 16:11 UTC, unicoooorn commented on internal/db/connection.go
> +func ConnectToDatabase() (*sql.DB, error) {
и еще ты вроде хотел дбшку пингануть внутри конструктора

2023-11-20 10:25 UTC, unicoooorn approved these changes, later dismissed

2023-11-20 10:48 UTC, unicoooorn requested changes
давай, немного осталось

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +		_, err := app.AddData("knowledge", elem, "knowledge_pk")
вот AddData точно удали и вместо него сделай голый SQL запрос прямо внутри AddKnowledge

2023-11-20 10:48 UTC, unicoooorn commented on internal/db/connection.go
> +	host, okHost := os.LookupEnv("DB_HOST")
обычно делают не несколько разных переменных типа ok, а просто после каждого получения проверяют 
if !ok, так меньше засоряется код
сделай так

2023-11-20 10:48 UTC, unicoooorn commented on internal/db/connection.go
> +	psqlconn := fmt.Sprintf(`host=%s port=%s user=%s password=%s dbname=%s sslmode=disable`, host, port, user, password, dbname)
а разве нет встроенного метода формирования строки подключения? посерчи

2023-11-20 10:48 UTC, unicoooorn commented on internal/db/connection.go
> +	if connErr := conn.Ping(); connErr != nil {
почему connErr? просто err

2023-11-20 10:48 UTC, unicoooorn commented on internal/db/connection.go
> +		return nil, errors.New("unable to load .env file")
у тебя возвращается только "unable to load .env file", хочется ещё err прикидывать
это можно сделать так например:
```go
return nil, fmt.Errorf( "unable to load .env file: %w", err)
```

2023-11-20 10:48 UTC, unicoooorn commented on internal/db/connection.go
> +		return nil, errors.New("unable to load .env file")
вообще старайся использовать либо fmt.Errrof, либо errors.New, мешать их не стоит
а вообще погугли чем отличаются, я не очень помню)))

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	contains, errCont := app.CheckIfContains(table, needed, column)
просто err

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	res, errAdd := app.db.Exec(`INSERT INTO knowledge(knowledge_pk) VALUES ($1)`, needed)
просто err

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	if contains || (errCont != nil && errCont != sql.ErrNoRows) {
сначала всегда проверяй на ошибку, потом уже проверяй согласно твоей бизнес-логике

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	contains, errCont := app.CheckIfContains(table, needed, column)
а зачем ты вообще проверяешь на существование, если тебе не позволит SQL вставить другой кортеж с таким же primary key? просто отлови ошибку sql.AlreadyExists или что-то такое

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	if contains || (errCont != nil && errCont != sql.ErrNoRows) {
никогда не сравнивай ошибки через == или != с чем либо, кроме nil
если хочешь поймать sql.ErrNoRows, то проверяешь с errors.Is(err, sql.ErrNoRows)
это связано с тем, что у тебя эта ошибка может быть во что то обернута и не быть ровно ошибкой NoRows. А errors.Is разворачивает ошибку и ищет там именно её

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	contains, errCont := app.CheckIfContains(table, needed, column)
метод CheckIfContains надо удалить и явно делать SQL запросы, когда надо узнать о нахождении кортежа в таблице

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	err := http.ListenAndServe(":8080", nil)
промежуточная err не нужна, просто
```go
return http.ListenAndServe(...)
```

2023-11-20 10:48 UTC, unicoooorn commented on internal/app/start.go
> +	err := app.AddKnowledge("14")
ну тут ты наверное хочешь ответить с кодом 200 или 500 у зависимости от результата операции?

2023-11-21 16:18 UTC, unicoooorn requested changes

2023-11-21 16:18 UTC, unicoooorn commented on internal/app/app.go
> +	errCont := app.db.QueryRow(`SELECT exists (SELECT 1 FROM knowledge WHERE $1 = $2 LIMIT 1)`, "knowledge_pk", elem).Scan(&contains)
просто err

2023-11-21 16:18 UTC, unicoooorn commented on internal/app/app.go
> +	_, errAdd := app.db.Exec(`INSERT INTO knowledge(knowledge_pk) VALUES ($1)`, elem)
просто err

2023-11-21 16:18 UTC, unicoooorn commented on internal/app/app.go
> +	errCont := app.db.QueryRow(`SELECT exists (SELECT 1 FROM knowledge WHERE $1 = $2 LIMIT 1)`, "knowledge_pk", elem).Scan(&contains)
и сразу проверяешь на ошибку, потому только проверяешь на contains

2023-11-21 16:18 UTC, unicoooorn commented on internal/app/app.go
> +	knowledges, errKnow := app.db.Query(`SELECT * FROM knowledge`)
просто err

2023-11-21 16:18 UTC, unicoooorn commented on internal/rest/handler.go
> +	err := http.ListenAndServe(":8080", nil)
```go
return http.ListenAndServe(":8080", nil)
```

2023-11-21 16:18 UTC, unicoooorn commented on internal/rest/handler.go
> +		return
return бесполезные, в Go выполняется только один кейс из свитча

2023-11-21 16:26 UTC, unicoooorn reviewed
ыыыы

2023-11-22 10:05 UTC, M-Koscheev commented on internal/db/connection.go
> +	psqlconn := fmt.Sprintf(`host=%s port=%s user=%s password=%s dbname=%s sslmode=disable`, host, port, user, password, dbname)
не нашел такого

2023-11-22 10:12 UTC, M-Koscheev commented on internal/db/connection.go
> +		return nil, errors.New("unable to load .env file")
буду использовать errors.New

2023-11-22 14:26 UTC, unicoooorn commented on internal/app/app.go
> +	sqlKnow, err := app.db.Query(`SELECT knowledge_pk FROM knowledge`)
а закрыть?????
```go
defer sqlKnow.Close()
```
и вообще нейминг не очень
не понятно что такое sqlKnow, обычно результат квери называют "rows", тогда ниже будет rows.Next() и rows.Scan(), выглядит понятнее

2023-11-22 14:27 UTC, unicoooorn commented on internal/db/connection.go
> +	host := os.Getenv("DB_HOST")
хитрюга)
можешь так оставить, но в коммерческой разработке бывает гораздо лучше написать побольше кода и упасть с ошибкой, чем подключаться к чему-нибудь с пустыми кредами))))

2023-11-22 14:30 UTC, unicoooorn commented on internal/db/connection.go
> +	conn, _ := sql.Open("postgres", psqlconn)
не понял, почему ошибку здесь опускаешь?
ошибка, которая возвращается из sql.Open, и ошибка, которая возвращается из conn.Ping - это в смысловом смысле разные ошибки
в текущем состоянии у тебя может зафейлится sql.Open и ты сделаешь conn.Ping() от conn == nil, и будет nil pointer dereference - паника)

2023-11-22 14:30 UTC, unicoooorn commented on internal/db/connection.go
> +	conn, _ := sql.Open("postgres", psqlconn)
sql.Open вернет тебе ошибку, например, если у тебя некорректная строка подключения
а conn.Ping может вернуть, например, из-за сетевой ошибки

2023-11-22 14:31 UTC, M-Koscheev commented on internal/db/connection.go
> +	host := os.Getenv("DB_HOST")
Тут в любом случае была бы ошибка. Ранее есть проверка на подключение к .env - т.е. здесь ошибка возникает только в том случае если нужных записей нет в .env, в таком случае я бросаю предупреждение, а ошибка выбросится в другом месте. Сложив 2+2 мы получим причину ошибки.

2023-11-22 14:33 UTC, unicoooorn commented on internal/rest/handler.go
> +		} else {
в го есть рекомендация - keep happy path to the left
то есть у тебя благоприятный сценарий (в данном случае - http.StatusOk) должен находиться как можно левее в твоем коде
то есть в данном случае у тебя бесполезный и усложняющий код else, лучше делать так
```go
data, err := h.app.GetAllKnowledges()
if err != nil {
    slog.Error("Error getting data from knowledge table", err)
    w.WriteHeader(http.StatusInternalServerError)
    return
}
w.Write([]byte(strings.Join(data, " ")))
w.WriteHeader(http.StatusOK)
```

2023-11-22 14:34 UTC, unicoooorn commented on internal/rest/handler.go
> +		} else {
это делается для того, чтобы читающий программист мог пробежаться по коду, не заглядывая в ветвления и обработки ошибок, и понять, как он должен работать В ИДЕАЛЕ
а любые отступы - это обработка ошибок или неожиданных ситуаций

2023-11-22 14:35 UTC, unicoooorn commented on internal/rest/handler.go
> +			w.WriteHeader(http.StatusCreated)
возвращай http.StatusOK)
я знаю, что в http много много кодов и хочется использовать их все, но если дергает метод, то в случае успеха ожидают 200)

2023-11-22 14:35 UTC, unicoooorn commented on internal/rest/handler.go
> +			w.WriteHeader(http.StatusCreated)
столько кодов нужны в гораздо более сложных случаев, в данном случае у тебя http.StatusOK и http.StatusCreated не отличаются

2023-11-22 14:37 UTC, unicoooorn commented on internal/rest/handler.go
> +			w.WriteHeader(http.StatusCreated)
можно пофантазировать и придумать ситуацию, в котором они отличаются - например, у тебя метод получает компетенцию по ID, а если такой нет - то он ее создает. Тогда будет смысловая разница между http.StatusOK и http.StatusCreated. Но это все равно спорно, я не уверен, что это ок)

2023-11-22 14:37 UTC, M-Koscheev commented on internal/rest/handler.go
> +		} else {
Сам говорил убрать returnы из handlerа)

2023-11-22 14:38 UTC, unicoooorn commented on internal/rest/handler.go
> +		addData := reqData.Get("knowledge")
такие строковые константы принято именовать и выносить наверх файла
типа
```go
const QueryKeyKnowledge = "knowledge"
```

2023-11-22 14:40 UTC, unicoooorn commented on internal/rest/handler.go
> +		addData := reqData.Get("knowledge")
это сделано для того, чтобы случайно не сделать ошибку при прописывании этого в нескольких местах
или, допустим, когда тебе нужно заменить, чтобы не бегать по коду
по этой же причине есть константы http.StatusOK, а то разраб ошибется на 1 цифру и вернет вызывающему хуй за воротник

2023-11-22 14:41 UTC, unicoooorn reviewed
давай братишка там чисто косметические изменения остались, за 10 минут можешь доделать

2023-11-22 15:01 UTC, unicoooorn commented on internal/rest/handler.go
> +		} else {
так и думал что ты так скажешь!
но нет, у тебя return были в каждой ветке там, и вроде не было статусов, потому не было понятно, какая из веток правильаня

2023-11-22 15:01 UTC, unicoooorn approved these changes

2023-11-22 15:38 UTC, merged